using System.Text.Json.Serialization;
using OpenCode.Client.Internal.Json;
using OpenCode.Client.Models;
using OpenCode.Client.Models.Events;
using OpenCode.Client.Requests;

namespace OpenCode.Client.Internal.Json;

/// <summary>
/// Source-generated JSON serialization context for AOT compilation.
/// Lists all types that are serialized/deserialized via the client.
/// </summary>
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(string))]

// Models
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(Project[]))]
[JsonSerializable(typeof(List<Project>))]
[JsonSerializable(typeof(IReadOnlyList<Project>))]
[JsonSerializable(typeof(PathInfo))]
[JsonSerializable(typeof(VcsInfo))]

// Session
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(Session[]))]
[JsonSerializable(typeof(List<Session>))]
[JsonSerializable(typeof(IReadOnlyList<Session>))]
[JsonSerializable(typeof(SessionStatus))]
[JsonSerializable(typeof(SessionStatusIdle))]
[JsonSerializable(typeof(SessionStatusRetry))]
[JsonSerializable(typeof(SessionStatusBusy))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, SessionStatus>))]
[JsonSerializable(typeof(Dictionary<string, SessionStatus>))]

// Messages
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(UserMessage))]
[JsonSerializable(typeof(AssistantMessage))]
[JsonSerializable(typeof(UserMessageWrapper))]
[JsonSerializable(typeof(AssistantMessageWrapper))]
[JsonSerializable(typeof(MessageWithParts))]
[JsonSerializable(typeof(MessageWithParts[]))]
[JsonSerializable(typeof(List<MessageWithParts>))]
[JsonSerializable(typeof(IReadOnlyList<MessageWithParts>))]
[JsonSerializable(typeof(IReadOnlyList<Message>))]

// Parts
[JsonSerializable(typeof(Part))]
[JsonSerializable(typeof(TextPart))]
[JsonSerializable(typeof(ReasoningPart))]
[JsonSerializable(typeof(FilePart))]
[JsonSerializable(typeof(ToolPart))]
[JsonSerializable(typeof(StepStartPart))]
[JsonSerializable(typeof(StepFinishPart))]
[JsonSerializable(typeof(SnapshotPart))]
[JsonSerializable(typeof(PatchPart))]
[JsonSerializable(typeof(AgentPart))]
[JsonSerializable(typeof(RetryPart))]
[JsonSerializable(typeof(CompactionPart))]
[JsonSerializable(typeof(SubtaskPart))]
[JsonSerializable(typeof(Part[]))]
[JsonSerializable(typeof(List<Part>))]
[JsonSerializable(typeof(IReadOnlyList<Part>))]

// ToolState
[JsonSerializable(typeof(ToolState))]
[JsonSerializable(typeof(ToolStatePending))]
[JsonSerializable(typeof(ToolStateRunning))]
[JsonSerializable(typeof(ToolStateCompleted))]
[JsonSerializable(typeof(ToolStateError))]

// FilePartSource
[JsonSerializable(typeof(FilePartSource))]
[JsonSerializable(typeof(FileSource))]
[JsonSerializable(typeof(SymbolSource))]

// PartInput
[JsonSerializable(typeof(PartInput))]
[JsonSerializable(typeof(TextPartInput))]
[JsonSerializable(typeof(FilePartInput))]
[JsonSerializable(typeof(AgentPartInput))]
[JsonSerializable(typeof(SubtaskPartInput))]

// Events
[JsonSerializable(typeof(ServerEvent))]
[JsonSerializable(typeof(GlobalEvent))]
[JsonSerializable(typeof(EventServerInstanceDisposed))]
[JsonSerializable(typeof(EventInstallationUpdated))]
[JsonSerializable(typeof(EventInstallationUpdateAvailable))]
[JsonSerializable(typeof(EventLspClientDiagnostics))]
[JsonSerializable(typeof(EventLspUpdated))]
[JsonSerializable(typeof(EventMessageUpdated))]
[JsonSerializable(typeof(EventMessageRemoved))]
[JsonSerializable(typeof(EventMessagePartUpdated))]
[JsonSerializable(typeof(EventMessagePartDelta))]
[JsonSerializable(typeof(EventMessagePartRemoved))]
[JsonSerializable(typeof(EventPermissionUpdated))]
[JsonSerializable(typeof(EventPermissionReplied))]
[JsonSerializable(typeof(EventSessionStatus))]
[JsonSerializable(typeof(EventSessionIdle))]
[JsonSerializable(typeof(EventSessionCompacted))]
[JsonSerializable(typeof(EventFileEdited))]
[JsonSerializable(typeof(EventTodoUpdated))]
[JsonSerializable(typeof(EventCommandExecuted))]
[JsonSerializable(typeof(EventSessionCreated))]
[JsonSerializable(typeof(EventSessionUpdated))]
[JsonSerializable(typeof(EventSessionDeleted))]
[JsonSerializable(typeof(EventSessionDiff))]
[JsonSerializable(typeof(EventSessionError))]
[JsonSerializable(typeof(EventFileWatcherUpdated))]
[JsonSerializable(typeof(EventVcsBranchUpdated))]
[JsonSerializable(typeof(EventTuiPromptAppend))]
[JsonSerializable(typeof(EventTuiCommandExecute))]
[JsonSerializable(typeof(EventTuiToastShow))]
[JsonSerializable(typeof(EventPtyCreated))]
[JsonSerializable(typeof(EventPtyUpdated))]
[JsonSerializable(typeof(EventPtyExited))]
[JsonSerializable(typeof(EventPtyDeleted))]
[JsonSerializable(typeof(EventServerConnected))]
[JsonSerializable(typeof(EventUnknown))]

// Other models
[JsonSerializable(typeof(Todo[]))]
[JsonSerializable(typeof(List<Todo>))]
[JsonSerializable(typeof(IReadOnlyList<Todo>))]
[JsonSerializable(typeof(Command[]))]
[JsonSerializable(typeof(List<Command>))]
[JsonSerializable(typeof(IReadOnlyList<Command>))]
[JsonSerializable(typeof(Agent[]))]
[JsonSerializable(typeof(List<Agent>))]
[JsonSerializable(typeof(IReadOnlyList<Agent>))]
[JsonSerializable(typeof(Config))]
[JsonSerializable(typeof(ConfigProvidersResponse))]
[JsonSerializable(typeof(ProviderListResponse))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, ProviderAuthMethod[]>))]
[JsonSerializable(typeof(Dictionary<string, ProviderAuthMethod[]>))]
[JsonSerializable(typeof(ProviderAuthAuthorization))]
[JsonSerializable(typeof(FileNode[]))]
[JsonSerializable(typeof(List<FileNode>))]
[JsonSerializable(typeof(IReadOnlyList<FileNode>))]
[JsonSerializable(typeof(FileContent))]
[JsonSerializable(typeof(FileStatus[]))]
[JsonSerializable(typeof(List<FileStatus>))]
[JsonSerializable(typeof(IReadOnlyList<FileStatus>))]
[JsonSerializable(typeof(FindMatch[]))]
[JsonSerializable(typeof(List<FindMatch>))]
[JsonSerializable(typeof(IReadOnlyList<FindMatch>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(Symbol[]))]
[JsonSerializable(typeof(List<Symbol>))]
[JsonSerializable(typeof(IReadOnlyList<Symbol>))]
[JsonSerializable(typeof(ToolIds))]
[JsonSerializable(typeof(ToolListItem[]))]
[JsonSerializable(typeof(List<ToolListItem>))]
[JsonSerializable(typeof(IReadOnlyList<ToolListItem>))]
[JsonSerializable(typeof(FileDiff[]))]
[JsonSerializable(typeof(List<FileDiff>))]
[JsonSerializable(typeof(IReadOnlyList<FileDiff>))]
[JsonSerializable(typeof(Pty))]
[JsonSerializable(typeof(Pty[]))]
[JsonSerializable(typeof(List<Pty>))]
[JsonSerializable(typeof(IReadOnlyList<Pty>))]
[JsonSerializable(typeof(LspStatus[]))]
[JsonSerializable(typeof(List<LspStatus>))]
[JsonSerializable(typeof(IReadOnlyList<LspStatus>))]
[JsonSerializable(typeof(FormatterStatus[]))]
[JsonSerializable(typeof(List<FormatterStatus>))]
[JsonSerializable(typeof(IReadOnlyList<FormatterStatus>))]
[JsonSerializable(typeof(McpStatus))]
[JsonSerializable(typeof(McpStatusConnected))]
[JsonSerializable(typeof(McpStatusDisabled))]
[JsonSerializable(typeof(McpStatusFailed))]
[JsonSerializable(typeof(McpStatusNeedsAuth))]
[JsonSerializable(typeof(McpStatusNeedsClientRegistration))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, McpStatus>))]
[JsonSerializable(typeof(Dictionary<string, McpStatus>))]
[JsonSerializable(typeof(McpAuthStartResponse))]
[JsonSerializable(typeof(TuiControlRequest))]
[JsonSerializable(typeof(Auth))]
[JsonSerializable(typeof(OAuth))]
[JsonSerializable(typeof(ApiAuth))]
[JsonSerializable(typeof(WellKnownAuth))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Permission))]

// Requests
[JsonSerializable(typeof(SessionCreateRequest))]
[JsonSerializable(typeof(SessionUpdateRequest))]
[JsonSerializable(typeof(SessionPromptRequest))]
[JsonSerializable(typeof(SessionCommandRequest))]
[JsonSerializable(typeof(SessionShellRequest))]
[JsonSerializable(typeof(SessionSummarizeRequest))]
[JsonSerializable(typeof(SessionRevertRequest))]
[JsonSerializable(typeof(SessionInitRequest))]
[JsonSerializable(typeof(SessionForkRequest))]
[JsonSerializable(typeof(PostSessionIdPermissionsPermissionIdRequest))]
[JsonSerializable(typeof(ConfigUpdateRequest))]
[JsonSerializable(typeof(McpAddRequest))]
[JsonSerializable(typeof(McpAuthCallbackRequest))]
[JsonSerializable(typeof(ProviderOauthAuthorizeRequest))]
[JsonSerializable(typeof(ProviderOauthCallbackRequest))]
[JsonSerializable(typeof(AppLogRequest))]
[JsonSerializable(typeof(TuiAppendPromptRequest))]
[JsonSerializable(typeof(TuiExecuteCommandRequest))]
[JsonSerializable(typeof(TuiShowToastRequest))]
[JsonSerializable(typeof(PtyCreateRequest))]
[JsonSerializable(typeof(PtyUpdateRequest))]
[JsonSerializable(typeof(PartInputRequest))]
[JsonSerializable(typeof(PartInputRequest[]))]
[JsonSerializable(typeof(List<PartInputRequest>))]
[JsonSerializable(typeof(IReadOnlyList<PartInputRequest>))]

public partial class OpenCodeJsonSerializerContext : JsonSerializerContext
{
    static OpenCodeJsonSerializerContext()
    {
        // This triggers the source generator to populate the context.
        // The actual initialization is done by the generator in the partial class.
    }
}
